# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "49da59fd7b0db0b1e1966e6198967ce0"
name = "Avada-app-test"
handle = "avada-app-test-10"
application_url = "https://we-bathrooms-legitimate-seasonal.trycloudflare.com/auth/shopify"
embedded = true

[webhooks]
api_version = "2025-07"

[auth]
redirect_urls = [
  "https://we-bathrooms-legitimate-seasonal.trycloudflare.com/auth/shopify/callback",
  "https://we-bathrooms-legitimate-seasonal.trycloudflare.com/authSa/shopify/callback",
  "https://we-bathrooms-legitimate-seasonal.trycloudflare.com/auth/shopify/embed/callback",
  "https://we-bathrooms-legitimate-seasonal.trycloudflare.com/auth/shopify/embed/callback/updateScopes",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
